name: Auto Release

on:
  push:
    tags:
      - '*.*.*'
    branches:
      - release

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag or branch
        id: version
        run: |
          # Check if this is a tag push or branch push
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            # Get the version from the tag
            VERSION=${GITHUB_REF#refs/tags/}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Extracted version from tag: $VERSION"
          elif [[ "$GITHUB_REF" == refs/heads/release ]]; then
            # For release branch, we need to determine the version
            # This could be from a file, git commit, or other source
            # For now, let's use a timestamp-based version
            VERSION="$(date +%Y.%m.%d)-$(git rev-parse --short HEAD)"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Generated version for release branch: $VERSION"
          else
            echo "Error: Unexpected ref $GITHUB_REF"
            exit 1
          fi

      - name: Extract release notes
        id: release-notes
        run: |
          # Extract content between ## version and the next ##
          VERSION="${{ steps.version.outputs.version }}"
          
          # Read the release notes file
          if [ -f "docs/release-notes.md" ]; then
            # Use awk to extract content between ## version: and next ##
            # Fix the awk syntax by properly escaping the version variable
            RELEASE_NOTES=$(awk -v version="$VERSION" '
              BEGIN { in_section = 0; content = "" }
              $0 ~ "^## " version ":" { in_section = 1; next }
              /^## [0-9]/ && in_section { exit }
              in_section { content = content $0 "\n" }
              END { print content }
            ' docs/release-notes.md)
            
            # Clean up the content (remove leading/trailing whitespace and empty lines)
            RELEASE_NOTES=$(echo "$RELEASE_NOTES" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | sed '/^$/d')
            
            if [ -z "$RELEASE_NOTES" ]; then
              echo "No release notes found for version $VERSION"
              RELEASE_NOTES="No release notes available for this version."
            fi
            
            echo "release_notes<<EOF" >> $GITHUB_OUTPUT
            echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            
            echo "Extracted release notes for version $VERSION"
            echo "Preview of release notes:"
            echo "$RELEASE_NOTES" | head -10
          else
            echo "Release notes file not found"
            echo "release_notes=Release notes file not found." >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.version.outputs.version }}
          body: ${{ steps.release-notes.outputs.release_notes }}
          draft: false
          prerelease: false 